{{- if .Values.ingress.enabled -}}
{{- $fullName := include "mastodon.fullname" . -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
    {{- if .Values.s3proxy.enabled }}
    {{- if .Values.s3proxy.tlsSecretName }}
    - hosts:
        {{- range .Values.s3proxy.hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .Values.s3proxy.tlsSecretName }}
    {{- end }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $fullName }}-web
              servicePort: web
          - path: {{ . }}api/v1/streaming
            backend:
              serviceName: {{ $fullName }}-streaming
              servicePort: streaming
          {{- end }}
    {{- end }}
    {{- if .Values.s3proxy.enabled }}
    {{- range .Values.s3proxy.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}-s3proxy
              servicePort: http
    {{- end }}
    {{- end }}
  {{- end }}
