apiVersion: v1
kind: Service
metadata:
  name: {{ include "mastodon.fullname" . }}-web
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
    app.kubernetes.io/instance: web
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: web
      protocol: TCP
      name: web
  selector:
    {{- include "mastodon.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/instance: web

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "mastodon.fullname" . }}-streaming
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
    app.kubernetes.io/instance: streaming
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: streaming
      protocol: TCP
      name: streaming
  selector:
    {{- include "mastodon.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/instance: streaming

---

{{- if .Values.s3proxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mastodon.fullname" . }}-s3proxy
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
    app.kubernetes.io/instance: s3proxy
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mastodon.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/instance: s3proxy
{{- end }}
